//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevWebEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talk()
        {
            this.Speakers = new HashSet<Speaker>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime When { get; set; }
        public int RoomId { get; set; }
        public int RoomId1 { get; set; }
    
        public virtual Room Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Speaker> Speakers { get; set; }
    }
}
