//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevWebEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        public int ListId { get; set; }
        public string Name { get; set; }
        public bool IsComplete { get; set; }
        public int Priority { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
